### ISSUE TITLE
Depreciation of methods for symfony 2.7.6

### ISSUE THREAD

**Issue by bertinl0609** [aimeos/aimeos-symfony2#11]
Hi,
i am using symfony 2.7.6 and was trying your bundles who looks promising even if i am passing a lot of time for decoding some things from documentation...

I had many DEPRECIATION warning... i ve listed the one i received on the list page from the frontend

DEPRECATED - The "_method" requirement of route "aimeos_shop_admin_file" in file "D:\xampp\htdocs\dev2\belch\vendor\aimeos\aimeos-symfony2/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" option instead.  +

DEPRECATED - The "_method" requirement of route "aimeos_shop_admin_json" in file "D:\xampp\htdocs\dev2\belch\vendor\aimeos\aimeos-symfony2/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" option instead.  +

DEPRECATED - The "_method" requirement of route "aimeos_shop_admin" in file "D:\xampp\htdocs\dev2\belch\vendor\aimeos\aimeos-symfony2/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" option instead.  +

DEPRECATED - The Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfProviderAdapter class is deprecated since version 2.4 and will be removed in version 3.0. Use the Symfony\Component\Security\Csrf\CsrfTokenManager class instead.  +

DEPRECATED - The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead.  +

DEPRECATED - Defining the initRuntime() method in the "form" extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended).  +

I am continuing my tests and will send you my comments about the Doc and some other tests.

**Comment by aimeos** [comment]
The SecurityContext thing is more complicated as we want to support all versions since Symfony 2.4. For the initRuntime() method I have no clue yet where this is used. At least it's not implemented by the Aimeos Symfony bundle but maybe by another bundle we are using.

**Comment by xabbuh** [comment]
@aimeos Is the security context actually used in this package at all? And you do not have any custom Twig extensions, do you?

**Comment by aimeos** [comment]
@xabbuh We don't use any custom Twig extensions but the security token for CSRF protection

**Comment by xabbuh** [comment]
@aimeos Can you point me to the code where this happens?

**Comment by aimeos** [comment]
@xabbuh Here it is: https://github.com/aimeos/aimeos-symfony2/blob/master/Service/View.php#L102

**Comment by xabbuh** [comment]
I am not sure I understand. The `CsrfTokenManager` class is not deprecated.

**Comment by aimeos** [comment]
@bertinl0609 Do you use any other bundles in your application?
I assume that another bundle creates the deprecation warnings

**Comment by bertinl0609** [comment]
Hi,
Here are the list of bundles used... 
    public function registerBundles()
    {
        $bundles = array(
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
            new Aimeos\ShopBundle\AimeosShopBundle(),
            new FOS\UserBundle\FOSUserBundle(),
        );

        if (in_array($this->getEnvironment(), array('dev', 'test'))) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
        }

**Comment by bertinl0609** [comment]
and the composer file:
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "aimeos/aimeos-symfony2": "~1.0",
        "sensio/generator-bundle": "^3.0",
        "friendsofsymfony/user-bundle": "~2.0@dev"

**Comment by aimeos** [comment]
I suspect the FOS user bundle to be the source of the remaining deprecation warnings.

**Comment by aimeos** [comment]
@bertinl0609: Are there any news on this?

**Comment by aimeos** [comment]
There was one remaining reference to "form.csrf_provider" in the admin interface which has been fixed now.

**Comment by aimeos** [comment]
All deprecated parts has been removed in the Aimeos Symfony bundle and it works now with Symfony 3 without problems in dev-master
