### ISSUE TITLE
Error satisfiable by aimeos

### ISSUE THREAD

**Issue by ialberdic** [aimeos/aimeos-symfony2#9]
I run composer update and I am getting this issue.

Can you please advise?

**Comment by aimeos** [comment]
Can you please add more details about your issue?

**Comment by ialberdic** [comment]
Just do a git clone of symfony aimeos and run composer. You will get the
error

**Comment by aimeos** [comment]
Which error? You haven't posted one, neither initially nor now!

**Comment by ialberdic** [comment]
I am really sorry, I had not enabled mysql for cli. I was working on a new laptop and I did not realise.
Apologies

**Comment by ialberdic** [comment]
Thank you for your help..aimeos is really great

**Comment by aimeos** [comment]
OK, no problem :-)
